title: Kunochi Support
description: Kunochi Shopping's support center to receive support and assistance.
theme: just-the-docs

url: https://support.kunochi.shop

aux_links:
  Roblox Group: https://www.roblox.com/communities/34484530/Kunochi-Shopping#!/about
  Discord Server: https://discord.gg/8C3Px8QZDV
  Store: https://www.roblox.com/games/18242896531/Kunochi-Store-Roleplay

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; Kunochi Shopping & Zeropoint. Unauthorized use of our documentation or resources may result in consequences</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

